pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "docker.io/chan0305/devops-app"
    }

    stages {

        stage('Clone Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Chan03051996/devops-end-to-end-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t docker.io/chan0305/devops-app:latest ./app'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-creds',
                    usernameVariable: 'USER',
                    passwordVariable: 'PASS'
                )]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin docker.io'
                    sh 'docker tag devops-app $DOCKER_IMAGE:latest'
                    sh 'docker push $DOCKER_IMAGE:latest'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl set image deployment/devops-app \
                devops-container=$DOCKER_IMAGE:latest
                '''
            }
        }
    }
}
